Add contribs and License
canonical/docker-registry-charm pull request #47
Opened 2021-01-29 15:02 UTC by evilnick

2022-04-14 17:59 UTC, addyess requested changes
small nit

2022-04-14 17:59 UTC, addyess commented on CONTRIBUTING.md
> +See [this page](https://github.com/charmed-kubernetes/kubernetes-docs/blob/master/pages/k8s/charm-docker-registry.md)
Page has moved right?

```suggestion
See [this page](https://discourse.charmhub.io/t/docker-registry-docs-index/6180)
```

2022-08-25 21:26 UTC, addyess commented
integration tests are being bitten by: https://github.com/juju/python-libjuju/issues/719

2022-08-26 13:21 UTC, addyess commented
@evilnick could you rebase?

2022-08-26 16:26 UTC, kwmonroe approved these changes

2022-08-26 16:26 UTC, merged